### ISSUE TITLE
How to install without bundle

### ISSUE THREAD

**Issue by souri84** [skyverge/woocommerce-memberships-rest-api-docs#3]
Hi,

I would like to install your package but bundle is not installed on my shared instance... so, how to do this ?

Thanks,

Thibaut

**Comment by unfulvio** [comment]
Hi. I'm not sure if I understand. This is just a repository for the documentation of the WooCommerce Memberships REST API. You can read the compiled documentation here: https://skyverge.github.io/woocommerce-memberships-rest-api-docs/

If you want to propose a change or contribute to the documentation, [please follow these instructions](https://github.com/skyverge/woocommerce-memberships-rest-api-docs#contributing).

If you need assistance with WooCommerce Memberships, please [open a support ticket](https://woocommerce.com/my-account/tickets).
