### ISSUE TITLE
REST API: How can i get about conditions according of plan.

### ISSUE THREAD

**Issue by GetAlongWell** [skyverge/woocommerce-memberships-rest-api-docs#4]
Hi, and thank you for your supported.
we install woo-commerce memberships 1.12.2. and create member plan for discount some product.
and in rest api document told us about collection data condition.
![image](https://user-images.githubusercontent.com/24242143/48668941-1c8e2980-eb2b-11e8-8052-38fd5811cbaf.png)

but there're not have any data about condition in plans api.
please help.

**Comment by unfulvio** [comment]
Hey there, @GetAlongWell 

Currently rules are not exposed in Memberships API responses. We are planning to add support later on, based on merchants and developers feedback. So currently the only way to access and manipulate rules is through PHP methods.

WooCommerce Memberships plan rules are stored in a WordPress option called `wc_memberships_rules`, therefore you could use the standard WordPress API to fetch the content of this option, which would return a serialized array of data. Each rule will have a reference to a membership plan ID it belongs to.

Please let me know what you are trying to build and how rules support in API endpoints can help you achieve that. This could be valuable feedback to extend the Memberships API. 

Thanks

**Comment by GetAlongWell** [comment]
Hi,
   we use woo-commerce as Service API and use Next.js for All Front-End and Our flexibility Development Team. and that point we want to get list of product in condition membership rules.

How we can get list data product in member codition with wordpress standard api? ( have to pass some parameter? )

Have you can show some sample code or something to get result like this?

Thank you for your supported.

**Comment by unfulvio** [comment]
hey @GetAlongWell 

When rules will be added to the API responses we'll make sure to add some examples as well. Meanwhile, please check the [WordPress API docs](https://developer.wordpress.org/rest-api/) and the [WooCommerce API docs](https://docs.woocommerce.com/document/woocommerce-rest-api/).

For WooCommerce Memberships support questions, [please send a support request](https://www.skyverge.com/support/). Thanks.
